# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-22 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_remove_project_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='rate.Profile'),
            preserve_default=False,
        ),
    ]
