# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-22 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_project_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
    ]
